import type { Metadata } from "next";
import { M_PLUS_Rounded_1c, Kiwi_Maru } from "next/font/google";
import "../style/globals.css";

const title = M_PLUS_Rounded_1c({
  variable: "--font-title",
  subsets: ['latin'],
  weight: ["100", "300", "400", "500", "700", "800", "900"]
})
const text = Kiwi_Maru({
  variable: "--font-text",
  subsets: ['latin'],
  weight: ["400"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        {children}
      </body>
    </html>
  );
}
